#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# borders colors

# bsps config normal_border_color "#B25BF5"
# bsps config active_border_color "#F55BB6"
# bsps config focused_border_color "#E45BF5"

bspc config normal_border_color  "#84b9a9"
bspc config focused_border_color "#e28b91"
bspc config urgent_border_color " #e9507c"
bspc config presel_border_color "#84b9a9"

# borders focus

bspc config focus_follows_pointer true
bspc config pointer_modifier super

# borders size 

bspc config border_width         2
bspc config window_gap          12


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

#AutoStart applications

sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
