## Import files (Colors, Fonts, Etc)
#import:
 # - ~/.config/alacritty/colors.yml
 # - ~/.config/alacritty/fonts.yml

## Set environment variables
env: TERM: alacritty
  WINIT_X11_SCALE_FACTOR: '1.0'

## Terminal window settings
window:
  dimensions:
    columns: 100
    lines: 30
  padding:
    x: 10
    y: 10

  decorations: full
  startup_mode: Windowed
  dynamic_title: true

## scrolling
  history: 10000
  multiplier: 3

## Background opacity
  opacity: 0.95

## Cursor
cursor:
  style:
    shape: Beam
    blinking: On

  unfocused_hollow: false


colors:
  background: "#181825"
## Live config reload
live_config_reload: true

